name: Android build

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64", "arm32", "x86", "x64" ]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: set up JDK
      uses: actions/setup-java@main
      with:
        distribution: zulu
        java-version: 27-ea

    - name: Build for Android ${{matrix.arch}}
      run: |
        export JAVA8_HOME=$JAVA_HOME_8_${{runner.arch}}
        export LWJGL_BUILD_ARCH=${{matrix.arch}}
        bash ci_build_android.bash

    - name: Upload modules release output
      if: ${{matrix.arch == 'arm64'}} # Only upload this once
      uses: actions/upload-artifact@main
      with:
        name: lwjgl-android-modules
        path: bin/RELEASE

    - name: Upload native build output
      uses: actions/upload-artifact@main
      with:
        name: lwjgl-android-natives-${{matrix.arch}}
        path: bin/out


    - uses: gradle/actions/setup-gradle@main
      with:
        validate-wrappers: false
        gradle-version: "8.14.3"

    - name: Download built native artifacts (arm64)
      uses: actions/download-artifact@main
      with:
          name: lwjgl-android-natives-arm64
          path: .github/workflows/android/assets/app_runtime/lwjgl/natives/arm64-v8a
    - name: Download built native artifacts (arm32)
      uses: actions/download-artifact@main
      with:
          name: lwjgl-android-natives-arm32
          path: .github/workflows/android/assets/app_runtime/lwjgl/natives/armeabi-v7a
    - name: Download built native artifacts (x64)
      uses: actions/download-artifact@main
      with:
          name: lwjgl-android-natives-x64
          path: .github/workflows/android/assets/app_runtime/lwjgl/natives/x86_64
    - name: Download built native artifacts (x86)
      uses: actions/download-artifact@main
      with:
          name: lwjgl-android-natives-x86
          path: .github/workflows/android/assets/app_runtime/lwjgl/natives/x86
    - name: Compile into one AAR
      run: |
          cd $GITHUB_WORKSPACE/.github/workflows/android
          gradle assembleRelease
    - name: Upload AAR
      uses: actions/upload-artifact@main
      with: 
          name: lwjgl-android-natives-aar
          path: .github/workflows/android/build/outputs/aar/lwjgl-natives-release.aar
