name: iOS build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Install dependencies
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install autoconf automake libtool

    - name: Build with CI build script
      run: |
        bash ci_build_ios.bash

    - name: Upload modules release output
      uses: actions/upload-artifact@v1
      with:
        name: lwjgl3-ios-modules
        path: bin/RELEASE

    - name: Upload native build output
      uses: actions/upload-artifact@v1
      with:
        name: lwjgl3-ios-natives
        path: bin/out
