name: Android build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: set up JDK
      uses: actions/setup-java@main
      with:
        distribution: temurin
        java-version: 21

    - name: Build for Android ${{matrix.arch}}
      run: |
        export JAVA8_HOME=$JAVA_HOME_8_X64
        export LWJGL_BUILD_ARCH=${{matrix.arch}}
        bash ci_build_android.bash

    - name: Upload modules release output
      if: ${{matrix.arch == 'arm64'}} # Only upload this once
      uses: actions/upload-artifact@main
      with:
        name: lwjgl3-android-modules
        path: bin/RELEASE

    - name: Upload native build output
      uses: actions/upload-artifact@main
      with:
        name: lwjgl3-android-natives-${{matrix.arch}}
        path: bin/out
