name: Android build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64"]
      fail-fast: false

    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 3

    - name: Download JDK
      run: |
          mkdir jdk22
          curl https://download.oracle.com/graalvm/22/latest/graalvm-jdk-22_linux-x64_bin.tar.gz | tar xz -C jdk22 --strip-components 1
          
    - name: Build for Android ${{matrix.arch}}
      run: |
        export JAVA_HOME=jdk22
        export JAVA8_HOME=$JAVA_HOME_8_${{runner.arch}}
        export LWJGL_BUILD_ARCH=${{matrix.arch}}
        bash ci_build_android.bash

    - name: Upload modules release output
      if: ${{matrix.arch == 'arm64'}} # Only upload this once
      uses: actions/upload-artifact@v4
      with:
        name: lwjgl3-android-modules
        path: bin/RELEASE

    - name: Upload native build output
      uses: actions/upload-artifact@v4
      with:
        name: lwjgl3-android-natives-${{matrix.arch}}
        path: bin/out
