# Generates javadoc for core + all bindings and uploads it to S3.
# The resulting javadoc is available at https://javadoc.lwjgl.org/
name: LWJGL Javadoc generation

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_PARAMS: --cache-control "public,must-revalidate,proxy-revalidate,max-age=0"
  LWJGL_BUILD_TYPE: nightly

jobs:
  macos:
    name: Javadoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - run: |
          git clone https://github.com/LWJGL-CI/OculusSDK.git ../OculusSDK
          mkdir jdk8
          mkdir jdk21
          curl -L https://cdn.azul.com/zulu/bin/zulu8.78.0.19-ca-jdk8.0.412-linux_x64.tar.gz | tar xz -C jdk8 --strip-components 1
          curl -L https://cdn.azul.com/zulu/bin/zulu21.34.19-ca-jdk21.0.3-linux_x64.tar.gz | tar xz -C jdk21 --strip-components 1
        name: Install dependencies
      - run: JAVA_HOME=$(pwd)/jdk8 ant -emacs hydrate-kotlinc clean-generated generate
        name: Generate bindings
      - run: JAVA_HOME=$(pwd)/jdk8 ant -emacs compile
        name: Build Java
      - run: JAVA8_HOME=$(pwd)/jdk8 JAVA_HOME=$(pwd)/jdk21 ANT_OPTS="-Djava.security.manager=allow" ant -emacs javadoc
        name: Generate javadoc
      - run: aws s3 sync bin/javadoc s3://lwjgl-javadoc/ --delete
        name: Upload javadoc to S3